import { chromium } from 'playwright';
console.log('connecting...');
const browser = await chromium.connectOverCDP('http://127.0.0.1:9222');
console.log('connected, contexts:', browser.contexts().length);
const page = await (browser.contexts()[0] || await browser.newContext()).newPage();
await page.setViewportSize({ width: 1400, height: 1600 });
console.log('navigating...');
await page.goto('http://localhost:8000/model_result/', { waitUntil: 'domcontentloaded', timeout: 60000 });
console.log('loaded, waiting for imgs...');
await page.waitForTimeout(12000);
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: 'audits/absolute_test_svg/model_result_gallery_view9.png' });
console.log('shot1 done');
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight * 0.45));
await page.waitForTimeout(2500);
await page.screenshot({ path: 'audits/absolute_test_svg/model_result_gallery_view9_mid.png' });
console.log('shot2 done');
await page.close();
console.log('OK');
